app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

app_viewpost:
    path:      /post/view/{id}/{slug}.{_format}
    defaults:  { _controller: AppBundle:App:viewpost, _format: html }
    requirements:
        _format:  html|rss
        id:     \d+

app_viewcategory:
    path:      /category/view/{id}.{_format}
    defaults:  { _controller: AppBundle:App:viewcategory, _format: html }
    requirements:
        _format:  html|rss
        id:     \d+

app_viewcategoryall:
    path:      /category/all
    defaults:  { _controller: AppBundle:App:viewcategoryall }

app_about:
    path:      /about
    defaults:  { _controller: AppBundle:App:about }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"